import streamlit as st
from fuzzywuzzy import process

# Predefined questions and answers
qa_pairs = {
    "hi": "Hello! How can I assist you today?",
    "hello": "Hi there! What can I help you with?",
    "what is your name": "Hello! My name is Cyber BOT How can I assist you today?",
    "hey": "Hey! How can I help you today?",
    "greetings": "Greetings! What would you like to know?",
    "good morning": "Good morning! How can I assist you today?",
    "good afternoon": "Good afternoon! What can I help you with?",
    "good evening": "Good evening! How can I assist you today?",
    "how are you?": "I'm just a bot, but thanks for asking! How can I help you?",
    "what's up?": "Not much! Just here to help you with your cybersecurity questions.",
    "what's going on?": "Just here to help! What would you like to know?",
    "how's it going?": "I'm doing well, thanks! How can I assist you?",
    "nice to meet you": "Nice to meet you too! What can I help you with today?",
    "long time no see": "Welcome back! How can I assist you?",
    "it's great to see you": "It's great to see you too! What questions do you have?",
    "how's your day?": "I'm just a program, but I'm here to help you! What do you want to know?",
    "hey there": "Hey there! How can I assist you today?",
    "hi there": "Hi there! What can I do for you?",
    "salutations": "Salutations! How can I assist you?",
    "yo": "Yo! What can I help you with?",
    "what brings you here?": "I'm here to answer your cybersecurity questions! What do you want to know?",
    "welcome": "Welcome! How can I assist you today?",
    "what is cybersecurity?": "Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks.",
    "what is phishing?": "Phishing is a method of trying to gather personal information using deceptive emails and websites.",
    "how to create a strong password?": "A strong password should be at least 12 characters long and include a mix of letters, numbers, and symbols.",
    "what is two-factor authentication?": "Two-factor authentication adds an extra layer of security by requiring not just a password but also a second factor, like a code sent to your phone.",
    "how to stay safe online?": "To stay safe online, always use strong passwords, enable two-factor authentication, and be cautious of suspicious emails or links.",
    "what is ransomware?": "Ransomware is a type of malicious software that encrypts a victim's files and demands a ransom for the decryption key.",
    "how to recognize a scam email?": "Look for poor grammar, unknown senders, and suspicious links as signs of a scam email.",
    "what is a firewall?": "A firewall is a network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules.",
    "what is malware?": "Malware is malicious software designed to harm, exploit, or otherwise compromise a computer system.",
    "what are the types of malware?": "Common types of malware include viruses, worms, Trojans, ransomware, and spyware.",
    "what is social engineering?": "Social engineering is the psychological manipulation of people into performing actions or divulging confidential information.",
    "how to protect against phishing attacks?": "To protect against phishing, be cautious of emails asking for personal information, verify the sender, and use security software.",
    "what is a DDoS attack?": "A Distributed Denial-of-Service (DDoS) attack is an attempt to make a machine or network resource unavailable by overwhelming it with traffic.",
    "what is encryption?": "Encryption is the process of converting information into code to prevent unauthorized access.",
    "what is a VPN?": "A Virtual Private Network (VPN) is a service that encrypts your internet connection and hides your online activity.",
    "how to secure my Wi-Fi network?": "To secure your Wi-Fi, use a strong password, enable WPA3 encryption, and regularly update your router firmware.",
    "what is identity theft?": "Identity theft is the act of obtaining and using someone's personal information without their consent, usually for financial gain.",
    "what is a secure website?": "A secure website uses HTTPS, meaning it has an SSL certificate that encrypts data exchanged between the user and the server.",
    "what is a security breach?": "A security breach occurs when an unauthorized party gains access to sensitive data or systems.",
    "how can I check if my data has been compromised?": "You can use services like Have I Been Pwned to check if your email or personal information has been involved in a data breach.",
    "what are strong passwords?": "Strong passwords are long, complex, and unique for each account, ideally containing a mix of letters, numbers, and symbols.",
    "what is cyber hygiene?": "Cyber hygiene refers to the practices and steps that users of computers and other devices take to maintain the health and security of their devices and data.",
    "what is a trojan horse?": "A Trojan horse is a type of malware that disguises itself as legitimate software to trick users into installing it.",
    "how to remove malware from my computer?": "To remove malware, use antivirus software to scan your system, and follow the software’s instructions to remove detected threats.",
    "what is a keylogger?": "A keylogger is a type of malware that records keystrokes to capture sensitive information such as passwords and credit card numbers.",
    "what is the principle of least privilege?": "The principle of least privilege states that users should have the minimum level of access necessary to perform their job functions.",
    "what are security patches?": "Security patches are updates released by software vendors to fix vulnerabilities that could be exploited by attackers.",
    "what is an SSL certificate?": "An SSL certificate is a digital certificate that provides authentication for a website and enables an encrypted connection.",
    "how to avoid online scams?": "To avoid online scams, be skeptical of unsolicited messages, research offers before acting, and verify the source.",
    "what is endpoint security?": "Endpoint security refers to the protection of endpoints or devices such as laptops, desktops, and mobile devices from security threats.",
    "what is a botnet?": "A botnet is a network of infected devices that are controlled by a cybercriminal to perform tasks, often used in DDoS attacks.",
    "what is ethical hacking?": "Ethical hacking involves testing computer systems and networks to identify vulnerabilities, with permission from the owner.",
    "what is a security policy?": "A security policy is a formal document that outlines how an organization manages its security and protects its assets.",
    "what is an intrusion detection system (IDS)?": "An IDS is a device or software application that monitors network traffic for suspicious activity and alerts administrators.",
    "what is an intrusion prevention system (IPS)?": "An IPS is a network security device that monitors network traffic for malicious activities and takes action to block them.",
    "how often should I change my passwords?": "It’s recommended to change your passwords every 3 to 6 months and immediately if you suspect a breach.",
    "what are the signs of a computer virus?": "Signs of a computer virus include slow performance, frequent crashes, unexpected pop-ups, and unusual behavior.",
    "how does phishing work?": "Phishing works by tricking users into providing sensitive information through fake emails or websites that appear legitimate.",
    "what is a zero-day vulnerability?": "A zero-day vulnerability is a security flaw that is unknown to the vendor and has not yet been patched.",
    "how to report a cybercrime?": "To report a cybercrime, contact your local law enforcement agency or file a report with a cybercrime reporting service.",
    "what is data breach notification?": "Data breach notification is the process of informing individuals when their personal information has been compromised.",
    "what are cyber threats?": "Cyber threats are potential malicious attacks that seek to unlawfully access data, disrupt services, or cause harm.",
    "what is the dark web?": "The dark web is a part of the internet that requires special software to access and is often associated with illegal activities.",
    "what is a digital footprint?": "A digital footprint is the trail of data you leave behind when you use the internet, including social media activity and online purchases.",
    "how to secure my personal data?": "To secure personal data, use strong passwords, enable two-factor authentication, and be cautious of sharing information online.",
    "what is public key infrastructure (PKI)?": "PKI is a framework that manages digital certificates and public-key encryption to secure communications and verify identities.",
    "what is a cyber attack?": "A cyber attack is any attempt to gain unauthorized access to a computer system or network with the intent to cause harm.",
    "what is digital forensics?": "Digital forensics is the process of collecting, analyzing, and preserving electronic data for use in investigations.",
    "what is an antivirus program?": "An antivirus program is software designed to detect, prevent, and remove malware from computer systems.",
    "what is a phishing simulator?": "A phishing simulator is a tool used to test and train employees on recognizing phishing attempts.",
    "what is threat hunting?": "Threat hunting is the proactive search for signs of malicious activity within an organization's networks and systems.",
    "what is cyber resilience?": "Cyber resilience is the ability to prepare for, respond to, and recover from cyber attacks and incidents.",
    "what is a honeypot?": "A honeypot is a security resource that appears to be a legitimate target for attackers but is actually a trap to study their behavior.",
    "what is insider threat?": "An insider threat is a security risk that originates from within the organization, typically from employees or contractors.",
    "what is a vulnerability assessment?": "A vulnerability assessment is a systematic review of security weaknesses in an information system.",
    "what is penetration testing?": "Penetration testing is a simulated cyber attack on a computer system to evaluate its security.",
    "what is the CIA triad?": "The CIA triad refers to the three core principles of cybersecurity: Confidentiality, Integrity, and Availability.",
    "what is cybersecurity awareness training?": "Cybersecurity awareness training educates employees about security threats and safe practices to protect against cyber attacks.",
    "what are the consequences of a data breach?": "Consequences of a data breach can include financial loss, legal penalties, and damage to reputation.",
    "what is a cybersecurity framework?": "A cybersecurity framework is a set of standards and best practices designed to manage cybersecurity risks.",
    "what is remote access?": "Remote access allows users to connect to a network or computer from a remote location.",
    "what is network segmentation?": "Network segmentation involves dividing a computer network into smaller parts to improve security and performance.",
    "what is risk assessment in cybersecurity?": "Risk assessment in cybersecurity is the process of identifying and evaluating risks to organizational assets.",
    "what is malware analysis?": "Malware analysis is the process of studying malware to understand its behavior and purpose.",
    "what are the phases of incident response?": "The phases of incident response typically include preparation, detection, analysis, containment, eradication, and recovery.",
    "what is threat modeling?": "Threat modeling is the process of identifying and prioritizing potential threats to a system.",
    "what is application security?": "Application security involves measures taken to improve the security of an application by identifying vulnerabilities.",
    "what is a security information and event management (SIEM) system?": "A SIEM system collects and analyzes security data from across an organization’s IT infrastructure.",
    "what is GDPR?": "The General Data Protection Regulation (GDPR) is a data protection law in the EU that governs how organizations handle personal data.",
    "what is a security breach response plan?": "A security breach response plan outlines the steps an organization will take to respond to a security incident.",
    "what is a digital certificate?": "A digital certificate is an electronic document used to prove the ownership of a public key.",
    "what is cybersecurity governance?": "Cybersecurity governance involves the framework of policies and procedures that guide an organization's cybersecurity efforts.",
    "what is a security operations center (SOC)?": "A SOC is a centralized unit that deals with security issues on an organizational and technical level.",
    "what is the difference between a threat and a vulnerability?": "A threat is a potential danger that could exploit a vulnerability, which is a weakness in a system that could be attacked.",
    "what is cloud security?": "Cloud security is the set of policies, controls, and technologies that protect data, applications, and infrastructure in cloud computing.",
    "what is a brute force attack?": "A brute force attack is a trial-and-error method used to decode encrypted data such as passwords.",
    "what is network security?": "Network security is the practice of protecting a computer network from intruders, whether targeted attackers or opportunistic malware.",
    "what is password manager?": "A password manager is a software application designed to store and manage your passwords securely.",
    "what is the Internet of Things (IoT)?": "The Internet of Things (IoT) refers to the interconnection of everyday devices to the internet, enabling them to send and receive data.",
    "what is a security audit?": "A security audit is a systematic evaluation of an organization’s information system's security measures.",
    "what is a supply chain attack?": "A supply chain attack targets an organization by compromising its suppliers or service providers.",
    "what is a digital rights management (DRM)?": "Digital rights management (DRM) is a set of access control technologies used to restrict the use of proprietary content.",
    "what is data encryption at rest?": "Data encryption at rest is the protection of data stored on disk using encryption methods.",
    "what is data encryption in transit?": "Data encryption in transit protects data being transmitted over a network.",
    "what is a security baseline?": "A security baseline is a minimum level of security controls and practices that must be implemented.",
    "what is a cyber threat intelligence?": "Cyber threat intelligence is information that organizations use to understand threats to their systems.",
    "what is the difference between a virus and a worm?": "A virus attaches itself to a host program, while a worm is a standalone malware that replicates itself to spread to other systems.",
    "what is digital identity?": "Digital identity is the online representation of an individual or organization, encompassing various attributes like usernames and profiles.",
    "what is a cyber kill chain?": "The cyber kill chain is a model that describes the stages of a cyber attack, from reconnaissance to action on objectives.",
    "what is a malicious insider?": "A malicious insider is an employee or contractor who intentionally misuses their access to harm the organization.",
    "what is a remote access trojan (RAT)?": "A RAT is a type of malware that allows an attacker to control a system remotely.",
    "what is a security token?": "A security token is a physical device or software-based tool that provides secure access to a system.",
    "what is continuous monitoring?": "Continuous monitoring involves ongoing observation of security and compliance to identify issues in real time.",
    "what is vulnerability management?": "Vulnerability management is the ongoing process of identifying, assessing, and mitigating security vulnerabilities.",
    "what is a malware sample?": "A malware sample is a copy of malicious software that can be analyzed for understanding its behavior.",
    "what is a phishing attack?": "A phishing attack is an attempt to trick individuals into providing sensitive information by impersonating a trustworthy entity.",
    "what is a security incident?": "A security incident is any event that compromises the confidentiality, integrity, or availability of data.",
    "what is a network attack?": "A network attack targets computer networks and can involve stealing data, disrupting services, or compromising devices.",
    "what is a computer virus?": "A computer virus is a type of malware that attaches itself to clean files and spreads throughout a computer system.",
    "what is a denial-of-service (DoS) attack?": "A DoS attack aims to make a machine or network resource unavailable by overwhelming it with traffic.",
    "what is a session hijacking?": "Session hijacking is a type of attack where an attacker takes over a user's session by stealing session cookies.",
    "what is the importance of cybersecurity?": "Cybersecurity is essential to protect sensitive data, maintain privacy, ensure business continuity, and uphold trust.",
    "what is an electronic signature?": "An electronic signature is a digital form of a signature that is used to authenticate the identity of the signer.",
    "what is a cybersecurity incident response team (CIRT)?": "A CIRT is a group of cybersecurity professionals responsible for preparing for and responding to security incidents.",
    "what is a Trojan virus?": "A Trojan virus is a type of malware that pretends to be legitimate software to deceive users.",
    "what is the difference between black hat and white hat hackers?": "Black hat hackers exploit vulnerabilities for malicious purposes, while white hat hackers use their skills for ethical purposes, such as security testing.",
    "what is an ethical hacker?": "An ethical hacker is a cybersecurity expert who uses their skills to help organizations identify and fix vulnerabilities.",
    "what is a rootkit?": "A rootkit is a collection of software tools that enable unauthorized access to a computer while hiding its presence.",
    "what is a clickjacking attack?": "A clickjacking attack tricks users into clicking on something different from what they perceive, potentially leading to unauthorized actions.",
    "what is cross-site scripting (XSS)?": "Cross-site scripting (XSS) is a security vulnerability that allows attackers to inject malicious scripts into web pages viewed by users.",
    "what is SQL injection?": "SQL injection is a code injection technique that exploits vulnerabilities in an application's software by executing malicious SQL statements.",
    "what is cybersecurity compliance?": "Cybersecurity compliance refers to adhering to laws, regulations, and standards that govern the protection of sensitive information.",
    "what is information security?": "Information security is the practice of protecting information from unauthorized access, use, disclosure, disruption, modification, or destruction.",
    "what is a cybersecurity framework?": "A cybersecurity framework is a structured set of guidelines for managing cybersecurity risks.",
    "what is data loss prevention (DLP)?": "Data loss prevention (DLP) refers to a strategy that ensures sensitive data is not lost, misused, or accessed by unauthorized users.",
    "what is the role of a chief information security officer (CISO)?": "A CISO is responsible for an organization's information and data security strategy and implementation.",
    "what is a digital wallet?": "A digital wallet is an electronic device or online service that allows individuals to make electronic transactions.",
    "what is social media security?": "Social media security involves protecting personal information shared on social media platforms from cyber threats.",
    "what is a cyber threat actor?": "A cyber threat actor is an individual or group that engages in malicious cyber activity.",
    "what is a security token service (STS)?": "A security token service (STS) issues security tokens to allow users access to protected resources.",
    "what is a data exfiltration?": "Data exfiltration is the unauthorized transfer of data from a computer or network.",
    "what is biometric authentication?": "Biometric authentication uses unique biological traits, such as fingerprints or facial recognition, to verify identity.",
    "what is cyber insurance?": "Cyber insurance is a policy that helps organizations manage the risk of cyber attacks and data breaches.",
    "what is a domain name system (DNS) attack?": "A DNS attack aims to exploit vulnerabilities in the domain name system to redirect traffic or compromise systems.",
    "what is a vulnerability scanner?": "A vulnerability scanner is a tool used to identify security weaknesses in systems or networks.",
    "what is a credential stuffing attack?": "A credential stuffing attack involves using stolen username and password combinations to gain unauthorized access to accounts.",
    "what is a certificate authority (CA)?": "A certificate authority is an entity that issues digital certificates for secure communications.",
    "what is network monitoring?": "Network monitoring involves continuously observing network traffic to identify anomalies and maintain performance.",
    "what is a digital certificate?": "A digital certificate is an electronic document that uses a digital signature to verify the identity of a person or organization.",
    "what is application programming interface (API) security?": "API security involves protecting APIs from security threats and vulnerabilities.",
    "what is an audit trail?": "An audit trail is a record of all activities related to data or an information system, used for compliance and security purposes.",
    "what is a cybersecurity training program?": "A cybersecurity training program educates employees on best practices and policies to protect sensitive information.",
    "what is a malware attack?": "A malware attack involves the installation of malicious software on a victim's device to disrupt operations or steal information.",
    "what is a bot attack?": "A bot attack uses automated scripts or bots to execute tasks, often for malicious purposes such as scraping data or launching DDoS attacks.",
    "what is a cyber threat landscape?": "The cyber threat landscape refers to the current state of cyber threats and vulnerabilities affecting organizations.",
    "what is a security framework?": "A security framework is a structured approach for managing security risks based on best practices and standards.",
    "what is vulnerability disclosure?": "Vulnerability disclosure is the process of reporting and resolving security vulnerabilities in software or systems.",
    "what is endpoint protection?": "Endpoint protection refers to securing endpoints such as laptops and mobile devices from security threats.",
    "what is email security?": "Email security involves protecting email accounts and communications from unauthorized access and cyber threats.",
    "what is a cyber security incident?": "A cybersecurity incident is any event that has compromised the confidentiality, integrity, or availability of data.",
    "what is threat intelligence?": "Threat intelligence is information about threats that helps organizations make informed decisions about their cybersecurity posture.",
    "what is a security control?": "A security control is a safeguard or countermeasure to protect information and information systems from threats.",
    "what is an incident response plan?": "An incident response plan is a documented strategy for addressing and managing the aftermath of a cybersecurity incident.",
    "what is a cyber risk assessment?": "A cyber risk assessment is the process of identifying and analyzing potential risks to an organization's cybersecurity posture.",
    "what is cloud computing security?": "Cloud computing security involves measures to protect data, applications, and services hosted in the cloud.",
    "what is a risk management framework?": "A risk management framework is a structured approach for managing risk in organizations.",
    "what is a zero trust security model?": "The zero trust security model is based on the principle of 'never trust, always verify,' requiring strict identity verification.",
    "what is a cyber threat assessment?": "A cyber threat assessment evaluates the potential threats to an organization's information and systems.",
    "what is a web application firewall (WAF)?": "A web application firewall is a security solution that monitors and filters HTTP traffic to and from a web application.",
    "what is a security breach notification law?": "A security breach notification law requires organizations to inform individuals when their personal data is compromised.",
    "what is incident management in cybersecurity?": "Incident management is the process of identifying, analyzing, and responding to security incidents.",
    "what is a cyber threat vector?": "A cyber threat vector is a path or method used by cyber attackers to gain access to a target system or network.",
    "what is a phishing kit?": "A phishing kit is a set of tools that attackers use to create phishing websites and conduct phishing campaigns.",
    "what is security by design?": "Security by design is the practice of integrating security measures into the design and development of software and systems.",
    "what is a threat actor?": "A threat actor is an individual or group that poses a threat to the security of an organization.",
    "what is cybersecurity metrics?": "Cybersecurity metrics are measures used to assess the effectiveness of security controls and the organization's overall security posture.",
    "what is a data breach response plan?": "A data breach response plan outlines the steps an organization will take in the event of a data breach.",
    "what is a cyber threat matrix?": "A cyber threat matrix is a tool used to categorize and analyze cyber threats based on various criteria.",
    "what is a cyber kill chain?": "The cyber kill chain is a model used to describe the stages of a cyber attack from reconnaissance to execution.",
    "what is malware distribution?": "Malware distribution refers to the methods and techniques used by cybercriminals to spread malware to victims.",
    "what is a security breach investigation?": "A security breach investigation is the process of examining and analyzing a security incident to determine its cause and impact.",
    "what is a cybersecurity roadmap?": "A cybersecurity roadmap is a strategic plan that outlines an organization's goals and initiatives for improving cybersecurity.",
    "what is a security operations center (SOC)?": "A security operations center (SOC) is a facility for monitoring and analyzing an organization's security posture.",
    "what is a cybersecurity framework?": "A cybersecurity framework is a set of guidelines and best practices for managing cybersecurity risks.",
    "what is a security risk assessment?": "A security risk assessment is the process of identifying and analyzing security risks within an organization.",
    "what is data integrity?": "Data integrity refers to the accuracy and consistency of data over its lifecycle.",
    "what is a cybersecurity incident report?": "A cybersecurity incident report is a document that outlines the details of a security incident and the response taken.",
    "what is network segmentation?": "Network segmentation involves dividing a network into smaller parts to improve security and performance.",
    "what is threat modeling?": "Threat modeling is the process of identifying and assessing potential threats to an organization's systems and data.",
    "what is a security audit?": "A security audit is a systematic evaluation of an organization's security measures and practices.",
    "what is a cybersecurity incident response team (CIRT)?": "A cybersecurity incident response team (CIRT) is a group of professionals responsible for managing security incidents.",
    "what is a digital rights management (DRM)?": "Digital rights management (DRM) is a set of access control technologies used to protect copyright-protected content.",
    "what is cybersecurity compliance?": "Cybersecurity compliance refers to adhering to laws, regulations, and standards related to data protection.",
    "what is a cyber threat landscape?": "The cyber threat landscape refers to the current state of cyber threats and vulnerabilities affecting organizations.",
    "what is data classification?": "Data classification is the process of organizing data into categories for better management and protection.",
    "what is malware detection?": "Malware detection is the process of identifying malicious software on a computer system.",
    "what is network forensics?": "Network forensics is the process of capturing and analyzing network traffic for security investigations.",
    "what is data encryption?": "Data encryption is the process of converting information into a code to prevent unauthorized access.",
    "what is cybersecurity governance?": "Cybersecurity governance is the framework that defines how an organization manages its cybersecurity risks.",
    "what is an advanced persistent threat (APT)?": "An APT is a prolonged and targeted cyber attack where an attacker gains access to a network and remains undetected.",
    "what is a security control assessment?": "A security control assessment evaluates the effectiveness of security controls in protecting systems and data.",
    "what is a security incident response plan (SIRP)?": "A SIRP outlines the actions to be taken in response to a security incident.",
    "what is a risk assessment?": "A risk assessment is a systematic process for evaluating potential risks to an organization's information and systems.",
    "what is a cybersecurity strategy?": "A cybersecurity strategy is a comprehensive plan that outlines how an organization will protect its information assets.",
    "what is a security breach?": "A security breach occurs when an unauthorized party gains access to sensitive data or systems.",
    "what is a data breach?": "A data breach is an incident where unauthorized access to confidential data occurs, often resulting in data theft.",
    "what is a cybersecurity framework?": "A cybersecurity framework is a set of guidelines that help organizations manage their cybersecurity risks.",
    "what is a cybersecurity maturity model?": "A cybersecurity maturity model is a framework that helps organizations assess their cybersecurity capabilities and practices.",
    "what is cybersecurity risk management?": "Cybersecurity risk management involves identifying, assessing, and mitigating risks to an organization's information assets.",
    "what is a cybersecurity incident management plan?": "A cybersecurity incident management plan outlines how to prepare for and respond to cybersecurity incidents.",
    "what is a cybersecurity awareness program?": "A cybersecurity awareness program educates employees about security threats and safe practices.",
    "what is an insider threat program?": "An insider threat program identifies and mitigates risks posed by employees and contractors.",
    "what is a penetration testing report?": "A penetration testing report documents the findings of a penetration test, including vulnerabilities and recommendations.",
    "what is a cyber threat hunting program?": "A cyber threat hunting program proactively searches for signs of malicious activity in an organization's network.",
    "what is a security vulnerability?": "A security vulnerability is a weakness in a system that can be exploited by attackers to gain unauthorized access.",
    "what is a data breach response team?": "A data breach response team is a group of individuals responsible for managing and responding to data breaches.",
    "what is a cybersecurity framework?": "A cybersecurity framework is a structured approach for managing cybersecurity risks based on best practices.",
    "what is a security incident response team (SIRT)?": "A security incident response team (SIRT) is responsible for preparing for and responding to security incidents.",
    "what is a cybersecurity risk assessment?": "A cybersecurity risk assessment evaluates the potential risks to an organization's cybersecurity posture.",
    "what is an application security assessment?": "An application security assessment evaluates the security of an application's code and architecture.",
    "what is a cyber threat intelligence program?": "A cyber threat intelligence program collects and analyzes information about cyber threats to enhance security.",
    "what is a cybersecurity compliance audit?": "A cybersecurity compliance audit evaluates whether an organization is adhering to relevant security regulations and standards.",
    "what is data governance?": "Data governance is the overall management of data availability, usability, integrity, and security in an organization.",
    "what is a digital certificate?": "A digital certificate is an electronic document used to prove the ownership of a public key and ensure secure communications.",
    "what is a cybersecurity risk mitigation plan?": "A cybersecurity risk mitigation plan outlines strategies to reduce identified risks to an organization's information assets.",
    "what is a security policy?": "A security policy is a document that outlines an organization's approach to managing and protecting its information assets.",
    "what is a cyber security incident management system?": "A cyber security incident management system is a set of processes and tools used to manage security incidents.",
    "what is cyber security best practices?": "Cybersecurity best practices are guidelines that help organizations improve their security posture and protect sensitive information.",
    "what is a cyber security incident report?": "A cybersecurity incident report is a document that outlines the details of a security incident and the actions taken to address it.",
    "what is a network penetration test?": "A network penetration test simulates cyber attacks to identify vulnerabilities in an organization's network.",
    "what is a data loss prevention policy?": "A data loss prevention policy outlines procedures for protecting sensitive data from loss or unauthorized access.",
    "what is a threat hunting strategy?": "A threat hunting strategy involves actively searching for threats within an organization's environment.",
    "what is a cyber threat landscape?": "The cyber threat landscape refers to the current state of cyber threats facing organizations, including types of attacks and vulnerabilities.",
    "what is a cyber security incident response framework?": "A cyber security incident response framework provides guidelines for responding to security incidents effectively.",
    "what is a cybersecurity threat model?": "A cybersecurity threat model is a structured approach to identifying, analyzing, and prioritizing potential threats to a system.",
    "what is security architecture?": "Security architecture is the design and structure of security measures within an organization's information systems.",
    "what is a cybersecurity framework?": "A cybersecurity framework is a set of standards, guidelines, and best practices for managing cybersecurity risks.",
    "what is a cyber security training program?": "A cybersecurity training program educates employees on security policies and best practices to mitigate risks.",
    "what is a security incident report template?": "A security incident report template is a predefined document structure used to record details about a security incident.",
    "what is data integrity?": "Data integrity refers to the accuracy and consistency of data throughout its lifecycle.",
    "what is a security audit trail?": "A security audit trail is a record of activities and changes to a system used for security assessments and compliance.",
    "what is application security testing?": "Application security testing involves evaluating an application's security to identify vulnerabilities and weaknesses.",
    "what is a vulnerability management program?": "A vulnerability management program systematically identifies, evaluates, and mitigates vulnerabilities in an organization's systems.",
    "what is a cyber security risk assessment?": "A cybersecurity risk assessment is the process of identifying and analyzing potential risks to an organization's cybersecurity posture.",
    "what is a cybersecurity incident response exercise?": "A cybersecurity incident response exercise tests an organization's ability to respond to security incidents through simulations.",
    "what is a security operations center (SOC) analyst?": "A SOC analyst is responsible for monitoring and responding to security incidents and threats within an organization.",
    "what is a risk management process?": "A risk management process is a systematic approach to identifying, analyzing, and addressing risks in an organization.",
    "what is a cybersecurity policy?": "A cybersecurity policy is a document that outlines the organization's approach to managing and protecting information security.",
    "what is a threat intelligence platform?": "A threat intelligence platform collects, analyzes, and shares threat intelligence data to enhance security operations.",
    "what is an attack surface?": "An attack surface is the total sum of vulnerabilities and potential entry points in an application or system that could be exploited by an attacker.",
    "what is a security compliance framework?": "A security compliance framework provides guidelines and best practices for organizations to achieve compliance with regulatory requirements.",
    "what is a cybersecurity audit?": "A cybersecurity audit is a comprehensive assessment of an organization's information systems and security measures to identify vulnerabilities and ensure compliance.",
    "what is incident detection?": "Incident detection is the process of identifying and recognizing security incidents in a timely manner.",
    "what is cybersecurity risk analysis?": "Cybersecurity risk analysis is the assessment of potential risks and vulnerabilities that could impact an organization's information security.",
    "what is a threat intelligence report?": "A threat intelligence report summarizes findings from threat intelligence research, providing insights into emerging threats and vulnerabilities.",
    "what is a cyber risk management strategy?": "A cyber risk management strategy is a comprehensive plan for identifying, assessing, and mitigating risks to an organization's information assets.",
    "what is a security operations center (SOC) manager?": "A SOC manager oversees the security operations center, ensuring effective monitoring and response to security incidents.",
    "what is a cybersecurity best practice?": "A cybersecurity best practice is a recommendation or guideline that helps organizations protect their information assets and reduce risks."
}

def get_response(user_input):
    # Get the best match from the predefined questions
    best_match, score = process.extractOne(user_input.lower(), qa_pairs.keys())
    if score > 70:  # You can adjust this threshold
        return qa_pairs[best_match]
    else:
        return "Sorry, I don't have an answer for that. Please try another question."

def main():
    st.title("Cybersecurity Chatbot")
    
    # Initialize session state to store chat history
    if 'chat_history' not in st.session_state:
        st.session_state.chat_history = []

    user_input = st.text_input("Ask me a cybersecurity question:")
    
    if st.button("Submit"):
        if user_input:
            response = get_response(user_input)
            # Add user question and bot response to chat history
            st.session_state.chat_history.append(f"User: {user_input}")
            st.session_state.chat_history.append(f"Cyber BOT: {response} \n")
            user_input = ""  # Clear the input field after submission

    if st.button("Clear Chat"):
        st.session_state.chat_history = []  # Clear chat history

    # Concatenate chat history for display with extra line breaks
    chat_history_text = "\n".join(st.session_state.chat_history)  # Double new line for spacing

    # Display the chat history in a single text area, making it accessible
    st.text_area("Chat History", chat_history_text, height=300)

if __name__ == "__main__":
    main()
